services:
  - type: web
    name: nbn-atlas-viewer
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
